version: '3.9'
services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: 172.21.200.3#53 # forward to unbound
    # Volumes store your data between container upgrades
    volumes:
      - '/etc/pihole:/etc/pihole'
      - '/etc/pihole/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      pihole_dns_network:
        ipv4_address: 172.21.200.2 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)


  unbound:
    build: ./unbound
    container_name: unbound
    hostname: unbound.local
    restart: unless-stopped
    ports:
      - "5335:53/tcp" # expose a different port (5335) so you can use it directly
      - "5335:53/udp"
    networks:
      pihole_dns_network:
        ipv4_address: 172.21.200.3 # <-- this is used by pihole as upstream DNS

  wg-easy:
      environment:
        # ⚠️ Required:
        # Change this to your host's public address
        - WG_HOST=34.237.12.16

        # Optional:
        # - PASSWORD=foobar123
        # - WG_PORT=51820
        # - WG_DEFAULT_ADDRESS=10.8.0.x
        -  WG_DEFAULT_DNS=172.21.200.2#53
        # - WG_MTU=1420
        # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
        # - WG_PERSISTENT_KEEPALIVE=25
        # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
        # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
        # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
        # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

      image: ghcr.io/wg-easy/wg-easy
      container_name: wg-easy
      volumes:
        - ./etc_wireguard:/etc/wireguard
      ports:
        - "51820:51820/udp"
        - "51821:51821/tcp"
      restart: unless-stopped
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1

      networks:
        pihole_dns_network:
          ipv4_address: 172.21.200.4 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)




networks:
  # Define a custom subnet for pihole so that unbound can be an upstream DNS on port 53
  pihole_dns_network:
    name: "pihole_dns_network"
    ipam:
      driver: default
      config:
        - subnet: 172.21.200.0/24
          gateway: 172.21.200.1
          ip_range: 172.21.200.128/25 # 172.21.200.129 - 172.21.200.254
